version: 1
default_environment: dev
project_id: 8350ba7d-458b-46bf-993e-7986445f7a3d
environments:
- name: dev
- name: staging
- name: prod
plugins:
  extractors:
  - name: tap-facebook
    variant: singer-io
    pip_url: git+https://github.com/singer-io/tap-facebook.git
    config:
      location: EU
      add_metadata_columns: true
      credentials_path: ${CREDENTIALS_FILE_PATH}
      start_date: '2024-01-30T00:00:00Z'
      access_token: ${ACCESS_TOKEN}
      api_version: v16.0
      include_deleted: 'false'
      insights_buffer_days: 7
      account_id: ${ACC_ID}
    select:
    - ads_insights.account_id
    - ads_insights.account_name
    - ads_insights.action_values
    - ads_insights.actions
    - ads_insights.ad_id
    - ads_insights.ad_name
    - ads_insights.adset_id
    - ads_insights.adset_name
    - ads_insights.campaign_id
    - ads_insights.campaign_name
    - ads_insights.canvas_avg_view_percent
    - ads_insights.canvas_avg_view_time
    - ads_insights.clicks
    - ads_insights.conversion_values
    - ads_insights.conversions
    - ads_insights.date_start
    - ads_insights.date_stop
    - ads_insights.impressions
    - ads_insights.inline_link_clicks
    - ads_insights.inline_post_engagement
    - ads_insights.objective
    - ads_insights.outbound_clicks
    - ads_insights.social_spend
    - ads_insights.spend
    - ads_insights.video_30_sec_watched_actions
    - ads_insights.video_p100_watched_actions
    - ads_insights.video_p25_watched_actions
    - ads_insights.video_p50_watched_actions
    - ads_insights.video_p75_watched_actions
    - ads_insights.website_ctr
  - name: tap-shopify
    variant: matatika
    pip_url: git+https://github.com/Matatika/tap-shopify.git@v0.3.1
  loaders:
  - name: target-bigquery
    variant: adswerve
    pip_url: git+https://github.com/adswerve/target-bigquery.git@0.12.0
    config:
      project_id: ${PROJ_ID}
      dataset_id: ${DATA_ID}
jobs:
- name: tap-facebook-europe-to-bigquery
  tasks:
  - tap-facebook target-bigquery
